name: release express app

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]    

# Job called build runs-on ubuntu-latest
jobs:

  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Print environment variables
      run: env
      
    - name: Check if secrets are available
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "DOCKERHUB_USERNAME is not set"
        else
          echo "DOCKERHUB_USERNAME is set"
        fi

        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "DOCKERHUB_TOKEN is not set"
        else
          echo "DOCKERHUB_TOKEN is set"
        fi
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: user/app:latest
